### ISSUE TITLE
v2 籌備

### ISSUE THREAD

**Issue by aldy120** [aldy120/youtuber-pk#40]
codepen: https://codepen.io/aldy120/pen/rNpPpBL

[When to use IMG vs. CSS background-image?](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image)

**Comment by aldy120** [comment]
put image into div.
```css
img {
  max-width: 100%
}
```
